# Task 1: Supervised Machine Learning Models 

In [1]:
import logging

log_file = r"C:\Users\symev\OneDrive\Training\Emeritus\capstone project\emeritus captone project\part3_machine_learning\supervised_ML_models.log"

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

logger.handlers.clear()

file_handler = logging.FileHandler(
    log_file,
    mode="w",
    encoding="utf-8"
)

formatter = logging.Formatter(
    "{asctime} - {levelname} - {name} - {message}",
    style="{",
    datefmt="%Y-%m-%d %H:%M:%S"
)

file_handler.setFormatter(formatter)
logger.addHandler(file_handler)

# Test that logging is working
logger.info("Logging started successfully.")

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import joblib

In [3]:
try:
    # #load dataset that has already been cleaned, feature engineered and proxy accident risk label added
    df = pd.read_csv(r"C:\Users\symev\OneDrive\Training\Emeritus\capstone project\emeritus captone project\Metro_Interstate_Traffic_Volume_Cleaned_FeatureEngineering_wProxy.csv")

    # Get number of rows and columns
    rows, columns = df.shape

    # Log successful data loading
    logger.info(
        "Raw CSV file loaded successfully: %d rows and %d columns.",
        rows,
        columns
    )

    # Display confirmation and first few rows
    print(f"\nFile loaded successfully!")
    print(f"Rows: {rows}")
    print(f"Columns: {columns}")
    print("\nFirst 5 rows:")
    print(df.head())

except FileNotFoundError:
    logger.error(f"File not found: '{file_path}'.")

except pd.errors.EmptyDataError:
    logger.error("The CSV file is empty.")

except pd.errors.ParserError:
    logger.error("The CSV file could not be parsed. Please check its format.")

except PermissionError:
    logger.error(f"Permission denied when trying to access '{file_path}'.")

except OSError as e:
    logger.error(f"Error reading the file: {e}")


File loaded successfully!
Rows: 48176
Columns: 38

First 5 rows:
  holiday    temp  rain_1h  snow_1h  clouds_all weather_main  \
0    None  288.28      0.0      0.0          40       Clouds   
1    None  289.36      0.0      0.0          75       Clouds   
2    None  289.58      0.0      0.0          90       Clouds   
3    None  290.13      0.0      0.0          90       Clouds   
4    None  291.14      0.0      0.0          75       Clouds   

  weather_description            date_time  traffic_volume  hour  ...  \
0    Scattered Clouds  2012-10-02 09:00:00            5545     9  ...   
1       Broken Clouds  2012-10-02 10:00:00            4516    10  ...   
2     Overcast Clouds  2012-10-02 11:00:00            4767    11  ...   
3     Overcast Clouds  2012-10-02 12:00:00            5026    12  ...   
4       Broken Clouds  2012-10-02 13:00:00            4918    13  ...   

   weather_is_clear  weather_is_not_clear  temp_scaled  traffic_volume_scaled  \
0                 0          

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48176 entries, 0 to 48175
Data columns (total 38 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   holiday                     48176 non-null  object 
 1   temp                        48176 non-null  float64
 2   rain_1h                     48176 non-null  float64
 3   snow_1h                     48176 non-null  float64
 4   clouds_all                  48176 non-null  int64  
 5   weather_main                48176 non-null  object 
 6   weather_description         48176 non-null  object 
 7   date_time                   48176 non-null  object 
 8   traffic_volume              48176 non-null  int64  
 9   hour                        48176 non-null  int64  
 10  day_of_week                 48176 non-null  int64  
 11  is_weekend                  48176 non-null  int64  
 12  hour_sin                    48176 non-null  float64
 13  hour_cos                    481

In [5]:
df.columns

Index(['holiday', 'temp', 'rain_1h', 'snow_1h', 'clouds_all', 'weather_main',
       'weather_description', 'date_time', 'traffic_volume', 'hour',
       'day_of_week', 'is_weekend', 'hour_sin', 'hour_cos', 'day_of_week_sin',
       'day_of_week_cos', 'holiday_flag', 'weather_Clear', 'weather_Clouds',
       'weather_Drizzle', 'weather_Fog', 'weather_Haze', 'weather_Mist',
       'weather_Rain', 'weather_Smoke', 'weather_Snow', 'weather_Squall',
       'weather_Thunderstorm', 'weather_is_clear', 'weather_is_not_clear',
       'temp_scaled', 'traffic_volume_scaled', 'congestion_category',
       'congestion_category_High', 'congestion_category_Low',
       'congestion_category_Medium', 'congestion_category_Severe',
       'high_risk'],
      dtype='object')

In [6]:
#dataset for classification
X = df[['temp', 'rain_1h', 'snow_1h', 'clouds_all', 'hour',
       'day_of_week', 'is_weekend', 'hour_sin', 'hour_cos','day_of_week_sin',
       'day_of_week_cos', 'holiday_flag',
       'weather_Clear', 'weather_Clouds', 'weather_Drizzle', 'weather_Fog',
       'weather_Haze', 'weather_Mist', 'weather_Rain', 'weather_Smoke',
       'weather_Snow', 'weather_Squall', 'weather_Thunderstorm',
       'weather_is_clear', 'weather_is_not_clear', 'temp_scaled']].values

y = df['high_risk'].values

In [7]:
#dataset for regression
Y = df['traffic_volume'].values

# Classification - logistic regression

In [8]:
logger.info("MILESTONE 1: Training Logistic Regression Classification model")


In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2 , random_state=1)

In [10]:
from sklearn.preprocessing import StandardScaler
print(x_test)
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
print(x_test)

[[2.73290000e+02 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 4.48410318e-01]
 [2.47760000e+02 0.00000000e+00 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 6.55368926e-02]
 [2.76930000e+02 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 5.02999400e-01]
 ...
 [2.86780000e+02 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 6.50719856e-01]
 [2.69420000e+02 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 3.90371926e-01]
 [2.66080000e+02 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 3.40281944e-01]]
[[-0.6266851  -0.1275949  -0.0282346  ... -0.62183607  0.62183607
  -0.6266851 ]
 [-2.632123   -0.1275949  -0.0282346  ...  1.60814087 -1.60814087
  -2.632123  ]
 [-0.34075506 -0.1275949  -0.0282346  ... -0.62183607  0.62183607
  -0.34075506]
 ...
 [ 0.4329842  -0.1275949  -0.0282346  ... -0.62183607  0.62183607
   0.4329842 ]
 [-0.93068215 -0.1275949  -0.0282346  ... -0.62183607  0.62183607
  -0.

In [11]:
from sklearn.linear_model import LogisticRegression
# clf = LogisticRegression(random_state=1)
clf = LogisticRegression(random_state=1 , penalty='l2' , solver= 'liblinear')
clf.fit(x_train, y_train)
yp = clf.predict(x_test)


In [12]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, yp))
print(classification_report(y_test, yp))

[[8971   65]
 [  56  544]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      9036
           1       0.89      0.91      0.90       600

    accuracy                           0.99      9636
   macro avg       0.94      0.95      0.95      9636
weighted avg       0.99      0.99      0.99      9636



In [13]:
from sklearn.metrics import roc_auc_score, roc_curve
auc_score = roc_auc_score(y_test, yp)
print(auc_score)

0.9497366091190792


In [14]:
# Save the trained model and scaler
joblib.dump(clf, "classification_logistic_regression_model.pkl")
joblib.dump(scaler, "standard_scaler.pkl")

logger.info("MILESTONE: Logistic Regression Classification Model and scaler saved successfully")


# Classification - SVM


In [15]:
logger.info("MILESTONE 2: Training Classification- SVM model")


In [16]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf2 = svm.SVC(kernel='poly') # Linear Kernel

#Train the model using the training sets
clf2.fit(x_train, y_train)

#Predict the response for test dataset
y_pred = clf2.predict(x_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[8986   50]
 [  36  564]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      9036
           1       0.92      0.94      0.93       600

    accuracy                           0.99      9636
   macro avg       0.96      0.97      0.96      9636
weighted avg       0.99      0.99      0.99      9636



In [18]:
from sklearn.metrics import roc_auc_score, roc_curve
auc_score = roc_auc_score(y_test, y_pred)
print(auc_score)

0.9672332890659583


In [19]:
# Save the trained model and scaler
joblib.dump(clf, "classification_SVM_model.pkl")
joblib.dump(scaler, "standard_scaler.pkl")

logger.info("MILESTONE: Classification - SVM Model and scaler saved successfully")

# Regression - linear 

In [20]:
logger.info("MILESTONE 3: Training Regression - linear model")


In [21]:
# Split X and y into training and test set 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=1)


In [22]:
from sklearn.linear_model import LinearRegression
regression_model = LinearRegression()
regression_model.fit(X_train, y_train)

LinearRegression()

In [23]:
predicted_price_train= regression_model.predict(X_train)
predicted_price_test= regression_model.predict(X_test)
y_test[0:10]
#this shows the real price 

array([4182,  677, 5525, 5572, 3418,  659, 4007, 4295,  781, 6459],
      dtype=int64)

In [24]:
predicted_price_test[0:10] #this is the estimated prices by the regression model

array([3938.50488281, 3275.80175781, 5664.54589844, 4382.95117188,
       3461.50585938,   88.28808594, 4404.92382812, 5047.74707031,
       1637.18066406, 3652.25292969])

In [42]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mean_absolute_error(y_train, predicted_price_train) #MAE for the training set

822.8621794878292

In [26]:
mean_absolute_error(y_test, predicted_price_test)  #MAE for the testing set

814.4715384122691

In [44]:
r2=r2_score(y_test,predicted_price_test)
print(r2)

0.7272587131298103


In [34]:
# Save the trained model and scaler
joblib.dump(regression_model, "regression_linear_model.pkl")
joblib.dump(scaler, "standard_scaler.pkl")

logger.info("MILESTONE: Regression linear model and scaler saved successfully")

# Regression - Random forest

In [35]:
logger.info("MILESTONE 4: Training Regression - random forest model")

In [50]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# Train model
rfr = RandomForestRegressor(n_estimators=100, random_state=1)
rfr.fit(X_train, y_train)

# Predict
y_pred = rfr.predict(X_test)

In [51]:
# Evaluate model
mae = mean_absolute_error(y_test, y_pred)
print(mae)

274.2296721421653


In [52]:
r2 = r2_score(y_test, y_pred)
print(r2)

0.9410836043098005


In [53]:
# Save the trained model and scaler
joblib.dump(rfr, "regression_logistic_model.pkl")

logger.info("MILESTONE: Regression random forest model saved successfully")